apiVersion: v1
kind: Service
metadata:
  name: orders-api-metrics
  namespace: app-demo
  labels:
    app: orders-api
spec:
  type: NodePort
  selector:
    app: orders-api
  ports:
    - name: http-metrics
      port: 8080          # service port
      targetPort: 8080    # container port
      nodePort: 31090     # pick a free NodePort in 30000-32767 range
